private:
  address: Test Address 1234
  bank_account: BANK_ACCOUNT
  billing_address: Billing Address 1234
  email: test@mail.com
  full_name: Full Name
  phone_number: +34123123123
  vat: 32342335Z

invoicing:
  activity_id: Activity
  contract_number: AINGAS
  customer_contract: 7949
  extension_number: 20395
  rate: 500
  last_invoice: 1000
